[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  //api "com.badlogicgames.ashley:ashley:$ashleyVersion"
  implementation "com.badlogicgames.box2dlights:box2dlights:$box2dlightsVersion"
  implementation "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  //api "com.badlogicgames.gdx:gdx-ai:$aiVersion"
  implementation "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
  //api "com.crashinvaders.vfx:gdx-vfx-core:$gdxVfxCoreVersion"
  //api "com.crashinvaders.vfx:gdx-vfx-effects:$gdxVfxEffectsVersion"
  implementation "com.esotericsoftware:kryo:$kryoVersion"
  //api "com.github.crykn.guacamole:core:$guacamoleVersion"
  //api "com.github.crykn.guacamole:gdx:$guacamoleVersion"
  implementation "com.github.crykn:kryonet:$kryoNetVersion"
  //api "com.github.crykn:libgdx-screenmanager:$screenManagerVersion"
  implementation "com.github.czyzby:noise4j:$noise4jVersion"
  //api "com.github.payne911:PieMenu:$pieMenuVersion"
  //api "com.github.tommyettinger:colorful:$colorfulVersion"
  //api "com.github.tommyettinger:crux:$cruxVersion"
  //api "com.github.tommyettinger:digital:$digitalVersion"
  //api "com.github.tommyettinger:formic:$formicVersion"
  //api "com.github.tommyettinger:gand:$gandVersion"
  //api "com.github.tommyettinger:gdcrux:$gdcruxVersion"
  //api "com.github.tommyettinger:gdx-TinyVG:$tinyVGVersion"
  //api "com.github.tommyettinger:kryo-digital:$kryoDigitalVersion"
  //api "com.github.tommyettinger:kryo-gand:$kryoGandVersion"
  //api "com.github.tommyettinger:kryo-gdcrux:$kryoGdcruxVersion"
  implementation "com.github.tommyettinger:kryo-libgdx:$kryoLibgdxVersion"
  implementation "com.github.tommyettinger:libgdx-texturepacker:$texturePackerOnlyVersion"
  implementation "com.github.tommyettinger:libgdx-textureunpacker:$textureUnpackerOnlyVersion"
  implementation "com.github.tommyettinger:libgdx-utils-box2d:$utilsBox2dVersion"
  implementation "com.github.tommyettinger:libgdx-utils:$utilsVersion"
  //api "com.github.tommyettinger:sjInGameConsole:$inGameConsoleVersion"
  implementation "de.golfgl.gdxcontrollerutils:gdx-controllerutils-mapping:$controllerMappingVersion"
  implementation "de.golfgl.gdxcontrollerutils:gdx-controllerutils-scene2d:$controllerScene2DVersion"
  implementation "space.earlygrey:shapedrawer:$shapeDrawerVersion"
  //api "space.earlygrey:simple-graphs:$simpleGraphsVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
  
  apply plugin: 'java-library'
  implementation "com.code-disaster.steamworks4j:steamworks4j:1.10.0"
  implementation "com.code-disaster.steamworks4j:steamworks4j-gdx:1.10.0"
  implementation "com.code-disaster.steamworks4j:steamworks4j-lwjgl3:1.10.0"
  implementation "com.code-disaster.steamworks4j:steamworks4j-server:1.10.0"

  //api "com.kotcrab.vis:vis-ui:1.5.9"

  //api "net.onedaybeard.artemis:artemis-odb:2.3.0"

  //api "com.strongjoshua:libgdx-inGameConsole:1.0.0"

}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
